name: Check Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: jetbrains

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle Sync
        run: ./gradlew tasks --all

      - name: Run Android Lint tool
        run: ./gradlew lint --configure-on-demand

  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ktlint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.5.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: ktlint

  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: jetbrains

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle Sync
        run: ./gradlew tasks --all

      - name: Build the `debug` output
        run: ./gradlew assembleDebug
