name: Publish Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  github-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle Sync
        run: ./gradlew tasks --all

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Add APK to Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/app-release.apk
